export const CARDS_PER_PLAYER = 8;

export const strains = [
	{
		Filename: '1.png',
		Strain: 'SKITTLEZ',
		Class: 'Common',
		Strength: 3,
		Magic: 6,
		Speed: 8,
		Agility: 7,
		Abliity: 'Sugar Rush',
		Description: 'With a burst of hyper speed, she zips around the battlefield.',
		Primary: 'c1395a',
		Secondary: 'f4c679'
	},
	{
		Filename: '2.png',
		Strain: 'ANIMAL MINTS',
		Class: 'Uncommon',
		Strength: 6,
		Magic: 12,
		Speed: 8,
		Agility: 7,
		Abliity: 'Frost Bond',
		Description: 'Gains +2 on each stat for every other animal-based card in play',
		Primary: '478473',
		Secondary: 'e6cc82'
	},
	{
		Filename: '3.png',
		Strain: 'RS-11',
		Class: 'Rare',
		Strength: 14,
		Magic: 10,
		Speed: 18,
		Agility: 17,
		Abliity: 'Overclock Core',
		Description: 'Once per game, RS-11 can enter Overdrive:\ngain +5 to all stats for 3 turns',
		Primary: '1c83a4',
		Secondary: '5cb6d0'
	},
	{
		Filename: '4.png',
		Strain: 'IDUKKI GOLD',
		Class: 'Legendary',
		Strength: 86,
		Magic: 90,
		Speed: 59,
		Agility: 65,
		Abliity: 'Summon Allies',
		Description: 'He summons 2 cards from his deck to the battlefield. If he dies, the do too.',
		Primary: 'cd8200',
		Secondary: 'cf9115'
	},
	{
		Filename: '5.png',
		Strain: 'GELATO',
		Class: 'Common',
		Strength: 5,
		Magic: 7,
		Speed: 4,
		Agility: 6,
		Abliity: 'Frost Drip',
		Description:
			'He releases a wave of enchanted chill, slowing enemies down and briefly numbing their abilities.',
		Primary: '417999',
		Secondary: '96b8b4'
	},
	{
		Filename: '6.png',
		Strain: 'SUPERBOOF',
		Class: 'Ultra Rare',
		Strength: 30,
		Magic: 22,
		Speed: 25,
		Agility: 23,
		Abliity: 'Boof Shield',
		Description:
			"Once per game, if Superboof is targeted by a Legendary card's ability or attack, he deflects the effect entirely and deals 5 damage back to them",
		Primary: '3d2771',
		Secondary: '7046a6'
	},
	{
		Filename: '7.png',
		Strain: 'WHITE RHINO',
		Class: 'Epic',
		Strength: 45,
		Magic: 30,
		Speed: 32,
		Agility: 39,
		Abliity: 'Rhino Hide',
		Description: 'He gains 1 STRENGTH whenever he is attacked by a rare card or higher.',
		Primary: '57a446',
		Secondary: '57a443'
	},
	{
		Filename: '8.png',
		Strain: 'NORTHERN LIGHTS',
		Class: 'Common',
		Strength: 2,
		Magic: 9,
		Speed: 3,
		Agility: 5,
		Abliity: 'Full Heal',
		Description: 'Heal a friendly card back to full health Can only be used once per game.',
		Primary: 'b76910',
		Secondary: 'ecbd5d'
	},
	{
		Filename: '9.png',
		Strain: 'STAR DAWG',
		Class: 'Common',
		Strength: 7,
		Magic: 4,
		Speed: 6,
		Agility: 5,
		Abliity: 'Cosmic Bark',
		Description:
			"His bark echoes through the galaxy, stunning enemies and lowering their next attack's power.",
		Primary: 'e09a2b',
		Secondary: 'ecc777'
	},
	{
		Filename: '10.png',
		Strain: 'GUSHERS',
		Class: 'Ultra Rare',
		Strength: 23,
		Magic: 28,
		Speed: 25,
		Agility: 27,
		Abliity: 'Juice Bomb',
		Description:
			'Gushers can explode, instantly destroying any one card of your choice. Gushers is destroyed as well.',
		Primary: '3a1b78',
		Secondary: '7c56ba'
	},
	{
		Filename: '11.png',
		Strain: 'SLURRICANE',
		Class: 'Uncommon',
		Strength: 12,
		Magic: 15,
		Speed: 14,
		Agility: 13,
		Abliity: 'Storm Spin',
		Description:
			'He spins into a cyclone of icy fruit, striking all enemies and leaving hem dazed and slowed.',
		Primary: '50335c',
		Secondary: 'd5ab6f'
	},
	{
		Filename: '12.png',
		Strain: 'BLUE CHEESE',
		Class: 'Epic',
		Strength: 49,
		Magic: 36,
		Speed: 32,
		Agility: 30,
		Abliity: 'Foul Odor',
		Description: 'His pungent stench.overwhelms all enemies, lowering their Speed by 20.',
		Primary: '266f2c',
		Secondary: '5f9d47'
	},
	{
		Filename: '13.png',
		Strain: 'STRAWBERRY COUGH',
		Class: 'Ultra Rare',
		Strength: 24,
		Magic: 29,
		Speed: 26,
		Agility: 25,
		Abliity: 'Cough Cloud',
		Description:
			"This card can take control of an enemy card's special ability and use it for one turn.",
		Primary: '483573',
		Secondary: '7b66ac'
	},
	{
		Filename: '14.png',
		Strain: 'SOUR DIESEL',
		Class: 'Common',
		Strength: 8,
		Magic: 4,
		Speed: 5,
		Agility: 4,
		Abliity: 'Diesel Fumes',
		Description: 'A cloud of noxious gas chokes the battlefield, dealing damage over time.',
		Primary: 'b9480d',
		Secondary: 'e8b651'
	},
	{
		Filename: '15.png',
		Strain: 'TRAINWRECK',
		Class: 'Common',
		Strength: 9,
		Magic: 4,
		Speed: 5,
		Agility: 4,
		Abliity: 'Steam Cloud',
		Description: "A cloud of steam cancels your enemy's next turn.",
		Primary: 'c3720d',
		Secondary: 'e8b54b'
	},
	{
		Filename: '16.png',
		Strain: 'ROADKILL SKUNK',
		Class: 'Legendary',
		Strength: 91,
		Magic: 74,
		Speed: 69,
		Agility: 66,
		Abliity: 'Rotten Reek',
		Description:
			'He sprays a noxious cloud so disorienting that it forces enemy cards to unleash their most powerful attack on their own',
		Primary: '2f2d07',
		Secondary: 'cea83c'
	},
	{
		Filename: '17.png',
		Strain: 'PINEAPPLE EXPRESS',
		Class: 'Uncommon',
		Strength: 10,
		Magic: 8,
		Speed: 16,
		Agility: 14,
		Abliity: 'Tropic Dash',
		Description:
			'He bursts forward in a jet of fruity steam, dodging enemy attacks and boosting the power of his next move.',
		Primary: 'c69722',
		Secondary: 'e0b84b'
	},
	{
		Filename: '18.png',
		Strain: 'AFGHAN KUSH',
		Class: 'Common',
		Strength: 6,
		Magic: 5,
		Speed: 2,
		Agility: 2,
		Abliity: 'Mountain Stance',
		Description:
			'This character becomes immune to all attacks for one turn and regenerates + 3 health.',
		Primary: 'ac6408',
		Secondary: 'e9bc5d'
	},
	{
		Filename: '19.png',
		Strain: 'CEREAL MILK',
		Class: 'Epic',
		Strength: 45,
		Magic: 41,
		Speed: 39,
		Agility: 35,
		Abliity: 'Cereal Grenade',
		Description: "Throws a cereal grenade that reduces an enemy's stats to 0 for 1 round",
		Primary: '165613',
		Secondary: '638c3f'
	},
	{
		Filename: '20.png',
		Strain: 'ZUSHI',
		Class: 'Rare',
		Strength: 14,
		Magic: 10,
		Speed: 15,
		Agility: 15,
		Abliity: 'Zushi',
		Description: 'If any Legendary card is in play, Zushi gains + 10 to all stats.',
		Primary: '306686',
		Secondary: '8bcee8'
	},
	{
		Filename: '21.png',
		Strain: 'PANAMA RED',
		Class: 'Legendary',
		Strength: 79,
		Magic: 80,
		Speed: 62,
		Agility: 69,
		Abliity: 'Inferno Surge',
		Description: "He deals 5 fire damage to all enemies on the battlefield every turn he's alive.",
		Primary: 'ce6c06',
		Secondary: 'd98c0d'
	},
	{
		Filename: '22.png',
		Strain: 'MOON ROCKS',
		Class: 'Epic',
		Strength: 41,
		Magic: 48,
		Speed: 34,
		Agility: 30,
		Abliity: 'Lunar Gravity',
		Description: 'Every second turn, he pulls an enemy card out of play for 1 round.',
		Primary: '15601b',
		Secondary: '6da24c'
	},
	{
		Filename: '23.png',
		Strain: 'WEDDING CAKE',
		Class: 'Uncommon',
		Strength: 14,
		Magic: 10,
		Speed: 7,
		Agility: 8,
		Abliity: 'Sugar Shield',
		Description: 'He cloaks himself in thick frosting that absorbs the next attack.',
		Primary: 'b68227',
		Secondary: 'ebc87f'
	},
	{
		Filename: '24.png',
		Strain: 'ALIEN MIRACLE COOKIES',
		Class: 'Rare',
		Strength: 16,
		Magic: 18,
		Speed: 15,
		Agility: 11,
		Abliity: 'Space Ship',
		Description: 'Using your spaceship, take an enemy in play of your choice.',
		Primary: '498bae',
		Secondary: '87c0e0'
	},
	{
		Filename: '25.png',
		Strain: 'CHEETOS',
		Class: 'Ultra Rare',
		Strength: 26,
		Magic: 23,
		Speed: 27,
		Agility: 25,
		Abliity: 'Inferno Roar',
		Description:
			'When played, Cheetos deals 5 damage to all enemy cards currently in play and lowers their Strength by 3 for 2 turns.',
		Primary: '3d0f75',
		Secondary: '5e2594'
	},
	{
		Filename: '26.png',
		Strain: 'PURPLE HAZE',
		Class: 'Common',
		Strength: 4,
		Magic: 8,
		Speed: 6,
		Agility: 5,
		Abliity: 'Mind Fog',
		Description: 'She drifts in like a daydream and leaves your thoughts scrambled.',
		Primary: '6b3f61',
		Secondary: 'e7c78e'
	},
	{
		Filename: '27.png',
		Strain: 'DIVINE JELLY',
		Class: 'Ultra Rare',
		Strength: 22,
		Magic: 30,
		Speed: 26,
		Agility: 24,
		Abliity: 'Celestial Drip',
		Description:
			'This card can bring back 2 cards from the dead, but sacrifices itself in the process.',
		Primary: '3e2b90',
		Secondary: '8969d0'
	},
	{
		Filename: '28.png',
		Strain: 'PURPLE PUNCH',
		Class: 'Uncommon',
		Strength: 20,
		Magic: 4,
		Speed: 5,
		Agility: 5,
		Abliity: 'Strength Surge',
		Description: 'He gains +1 strength when attacked.',
		Primary: 'b07212',
		Secondary: 'dcb765'
	},
	{
		Filename: '29.png',
		Strain: 'LONDON POUND CAKE',
		Class: 'Rare',
		Strength: 12,
		Magic: 17,
		Speed: 13,
		Agility: 14,
		Abliity: 'Cake Royalty',
		Description: 'When played with another cake card, it gives them +5 to all stats.',
		Primary: '3e658a',
		Secondary: '87afc7'
	},
	{
		Filename: '30.png',
		Strain: 'UK CHEESE',
		Class: 'Common',
		Strength: 6,
		Magic: 3,
		Speed: 5,
		Agility: 6,
		Abliity: 'Funk Bomb',
		Description: 'He blasts a wave of stinky funk that confuses enemies and lowers defenses.',
		Primary: 'c8811d',
		Secondary: 'e3b765'
	},
	{
		Filename: '31.png',
		Strain: 'JEALOUSY',
		Class: 'Ultra Rare',
		Strength: 22,
		Magic: 29,
		Speed: 24,
		Agility: 26,
		Abliity: 'Mirror of Malice',
		Description:
			"Once per game, Jealousy can copy an enemy card's special ability and use it as its own for 1 turn.",
		Primary: '612a8e',
		Secondary: '8445af'
	},
	{
		Filename: '32.png',
		Strain: 'DO-SI-DOS',
		Class: 'Rare',
		Strength: 18,
		Magic: 16,
		Speed: 12,
		Agility: 10,
		Abliity: 'Self Restore',
		Description: 'Once per game, this card can fully heal itself',
		Primary: '336097',
		Secondary: '93b2bb'
	},
	{
		Filename: '33.png',
		Strain: 'ZOAP',
		Class: 'Rare',
		Strength: 15,
		Magic: 16,
		Speed: 15,
		Agility: 11,
		Abliity: 'Sticky Lather',
		Description: 'If this card takes 5 or more damage from an attack, it gains +4 Magic.',
		Primary: '3b81a3',
		Secondary: '7dbada'
	},
	{
		Filename: '34.png',
		Strain: 'GMO',
		Class: 'Uncommon',
		Strength: 10,
		Magic: 17,
		Speed: 8,
		Agility: 9,
		Abliity: 'Stench Hex',
		Description:
			'He erupts in a blast of rotting sludge that weakens enemies, lowering their strength and magic for two turns.',
		Primary: '8a5f11',
		Secondary: 'cfae5b'
	},
	{
		Filename: '35.png',
		Strain: 'OREOZ',
		Class: 'Rare',
		Strength: 15,
		Magic: 12,
		Speed: 14,
		Agility: 11,
		Abliity: 'Dark Dipping',
		Description:
			"Once per game, Oreoz can dip into darkness and disable one enemy card's special ability for 2 turns.",
		Primary: '316ba0',
		Secondary: '74afd2'
	},
	{
		Filename: '36.png',
		Strain: 'GRAPE APE',
		Class: 'Uncommon',
		Strength: 18,
		Magic: 5,
		Speed: 8,
		Agility: 10,
		Abliity: 'Final Blow',
		Description: 'If this card dies, deal one final blow -\n-20 HP to enemy card',
		Primary: 'a4671f',
		Secondary: 'dab267'
	},
	{
		Filename: '37.png',
		Strain: 'WHITE WIDOW',
		Class: 'Epic',
		Strength: 45,
		Magic: 38,
		Speed: 31,
		Agility: 36,
		Abliity: 'Web Shot',
		Description: "Shoots out a sticky web; her children deal 5 damage to all opponent's cards",
		Primary: '70933d',
		Secondary: 'a3ae57'
	},
	{
		Filename: '38.png',
		Strain: 'BLUE RUNTZ',
		Class: 'Uncommon',
		Strength: 9,
		Magic: 17,
		Speed: 13,
		Agility: 12,
		Abliity: 'Trick Pop',
		Description:
			'He throws a stick of gum that explodes on impact, coating foes in sticky sweetness and freezing their next move.',
		Primary: '442874',
		Secondary: 'd7ab76'
	},
	{
		Filename: '39.png',
		Strain: 'PINK MALAWI',
		Class: 'Legendary',
		Strength: 61,
		Magic: 100,
		Speed: 76,
		Agility: 88,
		Abliity: 'Dismiss',
		Description: "She returns one of your opponent's cards back to your deck.",
		Primary: 'e66c71',
		Secondary: 'df746c'
	},
	{
		Filename: '40.png',
		Strain: 'PROJECT 4516',
		Class: 'Ultra Rare',
		Strength: 28,
		Magic: 26,
		Speed: 22,
		Agility: 25,
		Abliity: 'Containment Breach',
		Description:
			"Disables one enemy card's special ability and gains +5 STRENGTH for every card currently in play.",
		Primary: '5c2aa2',
		Secondary: '8555bd'
	},
	{
		Filename: '41.png',
		Strain: 'ANGOLA ROJA',
		Class: 'Legendary',
		Strength: 82,
		Magic: 95,
		Speed: 78,
		Agility: 84,
		Abliity: 'Sunborn Command',
		Description:
			"He seizes control of one of your opponent's cards with a radiant power unleashed through the ancient sun.",
		Primary: 'c77800',
		Secondary: 'd59a27'
	},
	{
		Filename: '42.png',
		Strain: 'ZUPREME',
		Class: 'Ultra Rare',
		Strength: 27,
		Magic: 26,
		Speed: 25,
		Agility: 23,
		Abliity: 'Crown Protocol',
		Description:
			"Zupreme can immediately cancel an enemy card's ability as it's being played and gain +3 to all stats for the next turn.",
		Primary: '3b1b7e',
		Secondary: '7f66b7'
	},
	{
		Filename: '43.png',
		Strain: 'PERMANENT MARKER',
		Class: 'Rare',
		Strength: 13,
		Magic: 16,
		Speed: 12,
		Agility: 15,
		Abliity: 'Stat Scribble',
		Description:
			"Change one of your own stats or enemy's stats to a number from 1-20\n(goes when card dies)",
		Primary: '2c6b9c',
		Secondary: '89bad4'
	},
	{
		Filename: '44.png',
		Strain: 'VENOM OG',
		Class: 'Uncommon',
		Strength: 15,
		Magic: 12,
		Speed: 9,
		Agility: 11,
		Abliity: 'Toxic Lunge',
		Description:
			'He leaps forward with venomous force, striking a single target and poisoning them for two turns.',
		Primary: '2a392c',
		Secondary: 'b6a460'
	},
	{
		Filename: '45.png',
		Strain: 'BIRTHDAY CAKE',
		Class: 'Common',
		Strength: 5,
		Magic: 4,
		Speed: 5,
		Agility: 4,
		Abliity: 'Lemon Blast',
		Description: 'Gains +10 to all stats when paired with the Wedding Cake card',
		Primary: 'bf6f0a',
		Secondary: 'f2c058'
	},
	{
		Filename: '46.png',
		Strain: 'LEMON HAZE',
		Class: 'Common',
		Strength: 6,
		Magic: 7,
		Speed: 3,
		Agility: 4,
		Abliity: 'Citrus Blast',
		Description: 'A citrus blast boosts all cards in play by +2\nfor all stats.',
		Primary: 'ab6e07',
		Secondary: 'e7bb58'
	},
	{
		Filename: '47.png',
		Strain: 'GIRL SCOUT COOKIES',
		Class: 'Common',
		Strength: 4,
		Magic: 3,
		Speed: 5,
		Agility: 6,
		Abliity: 'Sweet Trap',
		Description:
			"Her innocent charm lures enemies in-then bam! they're too dazzled to defend themselves.",
		Primary: 'eaa21a',
		Secondary: 'f6d07a'
	},
	{
		Filename: '48.png',
		Strain: 'DONNY BURGER',
		Class: 'Ultra Rare',
		Strength: 27,
		Magic: 22,
		Speed: 23,
		Agility: 24,
		Abliity: 'Grease Shield',
		Description: 'Immune to special abiliies for 4 turns after being played.',
		Primary: '543678',
		Secondary: '9171ba'
	},
	{
		Filename: '49.png',
		Strain: 'CHERRY PIE',
		Class: 'Uncommon',
		Strength: 15,
		Magic: 6,
		Speed: 10,
		Agility: 8,
		Abliity: 'Crimson Crust',
		Description: 'Absorbs the first hit and reflects half the damage back to the attacker.',
		Primary: '754d61',
		Secondary: 'd7b165'
	},
	{
		Filename: '50.png',
		Strain: 'SHERBERT',
		Class: 'Rare',
		Strength: 15,
		Magic: 18,
		Speed: 14,
		Agility: 11,
		Abliity: 'Cake Control',
		Description: 'If enemy has any cake or cookie cards in play, gain control of them.',
		Primary: '326697',
		Secondary: '88c2e2'
	},
	{
		Filename: '51.png',
		Strain: 'GORILLA GLUE',
		Class: 'Common',
		Strength: 9,
		Magic: 3,
		Speed: 5,
		Agility: 4,
		Abliity: 'Sticky Slam',
		Description: "Don't get too close - once he hits, you're stuck for hours.",
		Primary: 'e9b32b',
		Secondary: 'f6d890'
	},
	{
		Filename: '52.png',
		Strain: 'AMNESIA HAZE',
		Class: 'Common',
		Strength: 3,
		Magic: 9,
		Speed: 5,
		Agility: 4,
		Abliity: 'Forget-Me-Blast',
		Description:
			'Unleashes a confusing burst of energy that causes enemies to forget their next move.',
		Primary: '93745c',
		Secondary: 'f5ca7a'
	},
	{
		Filename: '53.png',
		Strain: 'ZOWAHH',
		Class: 'Rare',
		Strength: 13,
		Magic: 15,
		Speed: 20,
		Agility: 19,
		Abliity: 'Chaos Flip',
		Description: 'Flip a coin. If it lands on heads, you gain double stats.',
		Primary: '2f7ab7',
		Secondary: '75bbd8'
	},
	{
		Filename: '54.png',
		Strain: 'AK-47',
		Class: 'Epic',
		Strength: 46,
		Magic: 30,
		Speed: 43,
		Agility: 40,
		Abliity: 'Fire Arm',
		Description: 'He deals 5 damage to all enemies every turn.',
		Primary: '3f9a32',
		Secondary: '469c3b'
	},
	{
		Filename: '55.png',
		Strain: 'OG KUSH',
		Class: 'Common',
		Strength: 7,
		Magic: 8,
		Speed: 4,
		Agility: 3,
		Abliity: 'Kush Cloud',
		Description: 'The soothing smoke relaxes your mind and body, restoring your energy.',
		Primary: 'cd7d17',
		Secondary: 'f2cc77'
	}
];

